### ISSUE TITLE
请教预测模型的一些问题

### ISSUE THREAD

**Issue by nuts-bottles** [JiaxiSun/Intelligent-Distributed-Wireless-Radio-Map-Construction#1]
您好，我先前也参加了这个比赛。具体我尝试了通过基站坐标计算距离和方位角等信息，以及对于数据集增加高斯噪声，以增强输入特征，然后对每个维度单独Embedding。算法采用了XDeepFM，MLP使用了256/512/256+Relu，得分刚过20，传输5+08左右。学习了代码之后，有一点不太明白的地方想请教下：
1. 对于这类问题，是否相对较深的神经网络更适合，这块是如何想到这样设计的呢？
2. 在Embedding这块，坐标变换倒是比较容易想到，Postioning-encoding这块，不知您有无尝试过其它方案？

**Comment by JiaxiSun** [comment]
你好，
1. 之前我尝试过增加 hidden dim 的长度，但是这样带来的通信量的增长是 n^2, 但是对精度上没有显著的提升。因此我才用了小 hidden dim, 但是增加网络深度的做法。
2. 在position encoding 这部分，我除了可学习的编码器外还尝试了基于sin/cos 的编码，但是效果不如可学习的效果好。我也尝试过把和基站的距离d当做变量进行输入，但是没有尝试过对距离d做position encoding。

**Comment by nuts-bottles** [comment]
1. 这么做的话，我感觉，一个是可能会过拟合，另一个是这样比较难用上参数量化和剪枝。
2. Encoding这部分，也有可能是因为前面dim大小，抓取到信息有限。我这边调参时结果是，增加其它类型的编码能略微提升效果。

**Comment by JiaxiSun** [comment]
目前来说确实会出现过拟合问题，线上和线下有几分的gap，如果利用剪枝操作，应该可以提升泛华能力，减少过拟合。但是可能带来的问题是，利用已经训练好的大模型慢慢剪枝应该可以涨点，而直接从剪枝后的架构初始化参数重新训练，可能收敛不到更优的结果上。
